'''
How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2<=b <= 100

iterate through combinations and store outputs in list
sort list from smallest to largest
iterate through sorted list -- if previous term is different than current term then add
'''

term_list = list()
dist_term_list = list()
output = 0
for a in range(2,101):
    for b in range(2,101):
        output = a ** b
        term_list.append(output)

term_list.sort()
length = len(term_list) - 1
for x in range(0,length + 1):
    if x < length and term_list[x] != term_list[x + 1]:
        dist_term_list.append(term_list[x])
    elif x == length and term_list[x - 1] != term_list[x]:
        dist_term_list.append(term_list[x])

print len(dist_term_list)
print len(term_list)
